import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, Text, TextInput, useWindowDimensions, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { api } from "../../api";
import { AIChat } from "../../types";
import { colors } from "../../theme";
import { s } from "../../styles";
import { Empty } from "../../components/ui";
import { Modal, ScrollView } from "../../components/platform";
import { startDictation } from "../../utils/dictation";

export function AIWorkspace(){const [chats,setChats]=useState<AIChat[]>([]);const [active,setActive]=useState<AIChat|null>(null);const [message,setMessage]=useState("");const [title,setTitle]=useState("");const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);const desktop=useWindowDimensions().width>=960;const load=()=>api.aiChats().then(setChats).catch(()=>setChats([]));useEffect(()=>{void load()},[]);async function open(chat:AIChat){setActive(await api.aiChat(chat.id));setTitle(chat.title)}async function create(){const c=await api.createAIChat();setActive(c);setTitle(c.title);void load()}async function send(){if(!active||!message.trim())return;const text=message.trim();setMessage("");setBusy(true);try{await api.aiMessage(active.id,text);setActive(await api.aiChat(active.id));void load()}catch(e){setMessage(text);Alert.alert("AI недоступен",e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}}async function rename(){if(active&&title.trim()){await api.renameAIChat(active.id,title.trim());setActive({...active,title:title.trim()});void load()}}async function remove(){if(!active)return;await api.deleteAIChat(active.id);setActive(null);void load()}
  const consultationButton=<Pressable accessibilityRole="button" style={[s.aiNewButton,desktop&&s.aiNewButtonDesktop]} onPress={()=>void create()}><Ionicons name="add" size={20} color={colors.violet}/><Text style={s.aiNewButtonText}>Консультация</Text></Pressable>;
  return <View style={s.workspacePage}><ScrollView contentContainerStyle={s.aiWorkspaceList}>{desktop&&<View style={s.desktopSectionHeading}><View style={s.desktopSectionTitleRow}><Text style={s.desktopSectionTitle}>AI-консультант</Text>{consultationButton}</View><Text style={s.desktopSectionLead}>Отдельные диалоги для вопросов о здоровье и результатах исследований.</Text></View>}{chats.map(c=><Pressable key={c.id} style={s.aiChatCard} onPress={()=>void open(c)}><Text numberOfLines={1} style={s.aiChatCardTitle}>{c.title}</Text><Ionicons name="chevron-forward" size={20} color={colors.muted}/></Pressable>)}{!chats.length&&<Empty icon="sparkles-outline" title="Диалогов пока нет" text="Начните диалог, чтобы обсудить вопрос о здоровье с AI."/>}</ScrollView>{!desktop&&<View style={s.aiWorkspaceHeader}>{consultationButton}</View>}<Modal visible={!!active} animationType="slide" onRequestClose={()=>setActive(null)}><SafeAreaView style={s.chatPage}><KeyboardAvoidingView testID="ai-chat-page" behavior={Platform.OS==="ios"?"padding":undefined} style={s.chatPage}><View style={s.chatHeader}><Pressable style={s.iconButton} onPress={()=>setActive(null)}><Ionicons name="arrow-back" size={24}/></Pressable><TextInput style={s.chatTitleInput} value={title} onChangeText={setTitle} onBlur={()=>void rename()}/><Pressable style={s.iconButton} onPress={()=>void remove()}><Ionicons name="trash-outline" size={22} color={colors.coral}/></Pressable></View><ScrollView style={{flex:1}} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled">{active?.messages.map((m,i)=><View key={i} style={[s.messageBubble,m.role==="user"?s.userBubble:s.assistantBubble]}><Text style={[s.body,m.role==="user"&&{color:colors.white}]}>{m.content}</Text><Text style={[s.messageTime,m.role==="user"&&{color:"#FFFFFFAA"}]}>{new Date(m.created_at).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</Text></View>)}{busy&&<View style={[s.messageBubble,s.assistantBubble]}><ActivityIndicator color={colors.violet}/></View>}</ScrollView><View nativeID="keyboard-composer-dock" style={s.chatComposer}><Pressable style={s.iconButton} onPress={()=>startDictation(setMessage,setListening)}><Ionicons name={listening?"radio":"mic-outline"} size={23} color={colors.violet}/></Pressable><TextInput multiline style={s.chatInput} placeholder="Сообщение AI…" value={message} onChangeText={setMessage}/><Pressable disabled={busy||!message.trim()} style={s.sendButton} onPress={()=>void send()}><Ionicons name="arrow-up" size={22} color={colors.violet}/></Pressable></View></KeyboardAvoidingView></SafeAreaView></Modal></View>
}
